### ISSUE TITLE
Add option to skip fetch during `github create-pr`

### ISSUE THREAD

**Issue by mkondratek** [PawelLipski/git-machete#1047]
Is it needed to perform fetch every time I run github create-pr? It takes a while in the case of extensive projects and repos.

**Comment by PawelLipski** [comment]
Makes sense... the main purpose of the fetch was (IIRC, to be verified & documented in code) to make sure that the base branch really exists in the remote repo before opening a PR.

TBD, maybe even fetch should become opt-in (`--fetch` flag? kinda as in `traverse`) rather than opt-out (`--no-fetch` flag).

**Comment by PawelLipski** [comment]
Actually... if the purpose is to make sure that the base branch exists in the remote repo, maybe just try fetching this particular branch? or even do `git ls-remote`

**Comment by PawelLipski** [comment]
`git ls-remote` turned out to be a reasonable solution
