### ISSUE TITLE
Github squash and merge option

### ISSUE THREAD

**Issue by hwong557** [PawelLipski/git-machete#1123]
First of all, thank you for such a terrific piece of software. I use it all the time and I can't imagine working without it!

Suppose we have the following commits:
```
c0 (main)
c1
c2
c3
c4
c5 (feature1)
d1
d2 (feature2)
```
Suppose PR 1 is for `feature1` onto `main` and PR2 is for `feature2` onto `feature1`. Let's say PR 1 gets approved, but it is merged to `main` by a github squash and merge. If I do a `git machete traverse`, then git has to rebase `feature2` (with commits c0-c5 and d1-d2) onto a history consisting of just
```
C0 (main)
```
where `C0` is the squash of `c0`-`c5`. I end up getting weird history. Sorry I can't be more specific. I have only a shallow understanding of git but perhap the issue is git tries to rebase `c0`, ..., `c5` onto `C0` one at a time. Please let me know if there is something I can say or do to make this issue easier to diagnose and fix.

One might suggest squashing before I make the PR and that does work. But realistically, after I submit a PR, I have to add changes. It's a bit easier to point to a certain commit that addresses a reviewer's concern than it is to just amend `C0` with a bunch of fixes.

Thank you for reading and thank you for your work on this software!

**Comment by hwong557** [comment]
Seems like the discussion here is relevent: https://stackoverflow.com/questions/35901915/how-to-rebase-after-squashing-commits-in-the-original-branch

**Comment by PawelLipski** [comment]
Awww thanks :) I'll elaborate on the answer tomorrow!

**Comment by PawelLipski** [comment]
> Let's say PR 1 gets approved, but it is merged to main by a github squash and merge

Before getting to the core of the answer... note that you can also merge the PR but just fast-forward merging `feature1` to `main` locally and then pushing `main`. This can be performed with `git machete advance`... and fully resolves the problem of rebasing onto the squashed commits.

> I end up getting weird history

But assuming you still want/need to use squash-merges from GitHub... hmmm git-machete in general should handle that case as well. git-machete should figure out that only `d1` and `d2` should be rebased of `feature2` onto `C0` 🤔 If it doesn't happen (i.e. more commits are taken into this rebase), try the following:
1. Do not remove `feature1` right after merging its PR. See [this FAQ entry](https://github.com/VirtusLab/git-machete#sometimes-when-i-run-update-or-traverse-too-many-commits-are-taken-into-the-rebase-how-to-fix-that) for the reasons.
2. If you already don't remove `feature1` and/or keeping it around doesn't help, consider using less automated `git machete update`(which only does a rebase on a single branch) instead of `git machete traverse`. With `update`, you can specify the range of commits to rebase explicitly with `--fork-point=...` flag. In your case that would be sth like `git machete update --fork-point=c5`.

Pls let me know if this resolves your issues!

**Comment by hwong557** [comment]
Thnak you very much for your thorough and thoughtful response! Regarding your first suggestion, yes it doesn't work, but at work, I can't push anything directly to `main`. This is why I need Github squash-merges. I will give your suggestion a try next week... maybe I have to be more careful than spamming `git machete traverse -W -y`!

Thank you again for all your hard work and your reply!
