### ISSUE TITLE
Using `--whole` disables interactive rebase

### ISSUE THREAD

**Issue by sashaweiss-signal** [PawelLipski/git-machete#1205]
# Overview

When I run `git machete traverse` from a particular branch, I get interactive rebases. When I run `git machete traverse --whole`, I don't get interactive rebase.

## Expected behavior/command output

Interactive rebase during `traverse --whole`.

## Actual behavior/command output

Interactive rebase during `traverse`, but not during `traverse --whole`.

## `git` and `git machete` versions

```
git version 2.39.1
git-machete version 3.18.3
```

## Additional diagnostics info

I ran `git machete traverse --verbose` and `git machete traverse --verbose --whole`. In the former, the `git rebase` command includes `--interactive`, and in the latter it does not.

---

Thanks for maintaining this tool, and please let me know if there's additional context I can provide!

**Comment by PawelLipski** [comment]
Hey @sashaweiss-signal... `git machete traverse --whole` is equivalent to `git machete traverse -n --start-from=first-root --return-to=nearest-remaining`, where `-n` expands to `--no-interactive-rebase` (or `--no-edit-merge`, if the discouraged `--merge` mode is used). So there's **no** interactive rebase by design in `--whole`, as it's meant to roll over the entire tree in bulk.

Still, to have the behavior of `git machete traverse --whole` but with interactive rebases, you can use **`git machete traverse --start-from=first-root --return-to=nearest-remaining`** (no `-n`).

**Comment by sashaweiss-signal** [comment]
Got it – thanks for the rapid reply and thorough explanation, @PawelLipski. I'll update my aliases to use `--start-from=first-root` and that should work for my use case.

Gonna close the issue. Thanks again!
