### ISSUE TITLE
Display downstream PRs in PR chains description

### ISSUE THREAD

**Issue by aouaki** [PawelLipski/git-machete#1235]
When a PR description is updated (at creation or retarget/restack), only the upstream PRs are listed in the description's PR chain. 
It would be very useful to be able to also link the downstream PRs so that reviewers can easily jump to what's coming next (FYI graphite does this).

Thanks!

**Comment by PawelLipski** [comment]
Makes sense! I've got a pretty long queue of issues to sort out before that... but we'll get to that, eventually. Tentatively marking as milestone v3.26.0 (next minor release; there's surely gonna be a number of patch releases in the meantime).

I suppose a indented list (instead of the current flat, non-indented list) might be a good representation.

**Comment by PawelLipski** [comment]
Here's a teaser (https://github.com/PawelLipski/mergify-sandbox-1/pull/23) in a somewhat extreme example:

<img width="513" alt="image" src="https://github.com/user-attachments/assets/8cc8cd3a-27c3-4a37-a2b9-e87a771b615e">

WIP at PR https://github.com/VirtusLab/git-machete/pull/1306

**Comment by PawelLipski** [comment]
@tir38 v3.29.0 is about to be released, use `git config machete.github.prDescriptionIntroStyle full`
