### ISSUE TITLE
`create-{pr,mr}` doesn't take the existing `<!-- {start,end} git-machete generated -->` markers into account

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#1328]
Related: https://github.com/VirtusLab/git-machete/discussions/1283#discussioncomment-10670186

When `.git/info/description` looks like:

```
lolxd

<!-- start git-machete generated -->

<!-- end git-machete generated -->

foo bar
```

then the generated section blindly goes to the start, instead between the existing markers:

```
<!-- start git-machete generated -->

# Based on PR #25

(etc. etc.)

<!-- end git-machete generated -->

lolxd

<!-- start git-machete generated -->

<!-- end git-machete generated -->

foo bar

```

Let's also mention these markers in the docs + use `generated section ("intro")` instead of `intro`.

**Comment by frank-west-iii** [comment]
Hey @PawelLipski, I really appreciate you taking this suggestion. Unfortunately I don't think this works completely for my use case. Although I would be happy to be incorrect.

We don't use templates and I use `forceDescriptionFromCommitMessage` to get my PR body. I tried seeing if GH had a templating language that would put the commit message into the PR template and use both of these together, but couldn't find anything. 

Either way I'm just editing the PR body manually for now and moving it to the bottom instead of at the top.

Will keep digging to see if I can find a way to make these work together.

Edit:

Since I wrap am wrapping my machete commands in aliases I just ended up adding a new script to the string of commands which does what I need until I have some more time to figure out if this change works.

```bash
#!/usr/bin/env bash

body=$(gh pr view --json=body | jq -r '.body')
section=$(echo "$body" | sed -n '/<!-- start git-machete generated -->/,/<!-- end git-machete generated -->/p')
rest=$(echo "$body" | sed '/<!-- start git-machete generated -->/,/<!-- end git-machete generated -->/d')
new_body="$rest

$section"

gh pr edit --body "$new_body"
```
