### ISSUE TITLE
Add `prs` option to `list` command.

### ISSUE THREAD

**Issue by rifel123** [PawelLipski/git-machete#239]
Currently there is no possibility to check what are opened pull requests currently on Github, the only option to check it, is to visit repository page. Adding `prs` subcommand to `list` would solve this issue, plus it should be quite easy to implement, as sourcing pull requests from Github is already made in other places in code.

A regression test for this feature is needed as well.

**Comment by PawelLipski** [comment]
🤔

**Comment by PawelLipski** [comment]
I'd be wary of https://en.wikipedia.org/wiki/Inner-platform_effect. IIUC, this feature is in no way git-machete-specific &mdash; in fact, it's readily available via GitHub CLIs: either [`hub pr list`](https://github.com/github/hub) or [`gh pr list`](https://github.com/cli/cli). I use [the following function/alias (link)](https://github.com/PawelLipski/utils/blob/master/bashrc-append.sh#L167) myself.

**Comment by PawelLipski** [comment]
Wrt inner-platform effect... pls note that all (maybe there're some exceptions, but I can't think of any now) features of git-machete provide some extra value over vanilla git... even if these git-machete features have some close vanilla-git counterparts, e.g.:

* `git machete fork-point` is similar to [`git merge-base --fork-point`](https://git-scm.com/docs/git-merge-base#Documentation/git-merge-base.txt---fork-point), but with an extra bonus of taking into account reflogs of all local branches and their remote tracking branches, not just a single specified branch
* `git machete reapply`, `git machete update` are pretty similar to `git rebase --interactive --fork-point --onto ...`, but uses the upstream from `.git/machete` file if possible, and uses `git machete fork-point` rather than `git merge-base --fork-point` under the hood
* `git machete advance` is pretty similar to `git merge --ff-only`, but again, with a few things provided automatically based on `.git/machete`
* similarly for `git machete diff`, `git machete log` vs `git diff`, `git log`

**Comment by PawelLipski** [comment]
And most notably, your very own `git machete github create-pr` and `checkout-pr` also mimic the functionality of `gh`/`hub` CLIs... but again, with git-machete specific behavior added on the top
