### ISSUE TITLE
git machete traverse didn't work

### ISSUE THREAD

**Issue by kgadek** [PawelLipski/git-machete#318]
# Overview

- Working on this repo.
- Made more commits on feature branch.
- `git push` new commits to feature branch
- `git fetch`- develop behind upstream
- I'm on feature branch, execute `git machete traverse` - "nothing left to update"
- `git checkout master`, then `git machete traverse` - performs necessary updates

## Expected behavior/command output

I'm not sure if this is as designed, but I've expected for `git machete traverse` to work the same regardless what is checked out. `git machete traverse --help`:

> Traverses the branch dependency tree in pre-order (i.e. simply in the order as they occur in the definition file) and for each branch

## Actual behavior/command output

![image](https://user-images.githubusercontent.com/185848/138897211-b3255d37-dd2d-4a2f-8108-3e04f2a3377e.png)

## `git` and `git machete` versions

```
git version 2.33.1
git machete version 3.4.1
```

**Comment by kgadek** [comment]
Self reference:
- `git push`: `626b231..34eef82  issue/290-fish-completion -> issue/290-fish-completion`
- `git fetch`: `e37f8d8..354353e  develop              -> upstream/develop`

**Comment by PawelLipski** [comment]
Okay! that's an expected behavior: `traverse` by default starts from the current branch. This is configurable, however: either via `--start-from=...` flag, via an uber-flag `--whole/-w`, or uber-uber-flag `-W` (and in fact, typically I'm using `git machete traverse -W`).

Anyway! to make it more clear I'd do the two following improvements:
1. If `traverse` **instantly** reaches the end of the tree (i.e. without any action even being suggested to the user), let's change the message from the current `Reached ... nothing left to update` to sth like `Tip: traverse by default starts from the current branch, use (flags) to change this behavior`.
TBD if we want to specially handle the case where nothing _would_ have happened anyway even if we started from the first branch of .git/machete, i.e. the case of all edges green & all branches in sync with remote. Maybe just specially handle the case with the current branch being the first branch in .git/machete?
2. Update the piece of docs referenced by Konrad so that it mentions the default-but-configurable starting point.

**Comment by rifel123** [comment]
closed with #331
