### ISSUE TITLE
Branch-switch logic in `github checkout-prs` still not perfect :/

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#541]
![image](https://user-images.githubusercontent.com/3383210/171188122-bd5ac24e-2e10-4db3-bd76-18373c5c8d28.png)

Well.... I'd simply expect for the PR \#883 to be checked out 😅 and it doesn't happen

Same for `g m github checkout-prs --by=mkondratek`, I'd expect his only PR (\#870) to be checked out, but it doesn't happen

**Comment by amalota** [comment]
So the current logic doesn't switch the branch associated with the PR if that branch is already present in the managed branches. I propose to change it so that the branch will get checked out when:
- there is only single PR that meets the requirements (checkout-prs SINLGE_PR_NR / --by=USER / --all / --mine) -> stays the same
- it does not matter whether branch associated with that single PR is already present in the managed branches -> changed

@PawelLipski wdyt?

**Comment by PawelLipski** [comment]
Okay! let's proceed with the above ☝🏻
